from __future__ import annotations

import streamlit as st

from dashboard.auth_gate import require_authenticated_role
from dashboard.components.cards import render_feature_hero, render_prompt_actions, render_section_intro
from dashboard.components.header import render_page_header
from dashboard.components.sidebar import render_app_sidebar
from dashboard.services.copilot_reports import (
    build_copilot_report_focus,
    list_copilot_reports,
    load_copilot_report_bundle,
    summarize_copilot_reports,
)


AUTH_STATE = require_authenticated_role("OPERATOR")
render_app_sidebar(brand_pills=("Operator Access", "Read-Only AI"))

summary = summarize_copilot_reports()
reports = list_copilot_reports(limit=30)

render_page_header(
    "Copilot Reports",
    "Read-only repo, safety, drift, simulation, and strategy-lab artifacts generated by the AI copilot layer.",
    badges=[
        {"label": "Role", "value": str(AUTH_STATE.get("role") or "OPERATOR")},
        {"label": "Reports", "value": str(int(summary.get("report_count") or 0))},
        {"label": "Latest", "value": str(summary.get("latest_kind") or "unknown").replace("_", " ").title()},
    ],
)

render_feature_hero(
    eyebrow="AI Copilot",
    title="Evidence Packets, Not Control Buttons",
    summary="Review what the copilot found without granting it any new runtime authority.",
    body=(
        "Every artifact on this page is read-only. The copilot can review diffs, audit safety posture, detect drift, "
        "run paper-only simulations, and summarize strategy evidence, but it cannot arm trading or modify live state from here."
    ),
    badges=[
        {"text": "Read Only", "tone": "success"},
        {"text": f"{int(summary.get('report_count') or 0)} reports", "tone": "default"},
        {"text": str(summary.get("latest_kind") or "unknown").replace("_", " ").title(), "tone": "muted"},
    ],
    metrics=[
        {
            "label": "Warn / Critical",
            "value": str(
                int(dict(summary.get("severity_counts") or {}).get("warn", 0))
                + int(dict(summary.get("severity_counts") or {}).get("critical", 0))
            ),
            "delta": "Latest report severities",
        },
        {
            "label": "Repo Reviews",
            "value": str(int(dict(summary.get("kind_counts") or {}).get("repo_review", 0))),
            "delta": "Diff review artifacts",
        },
        {
            "label": "Lab Runs",
            "value": str(
                int(dict(summary.get("kind_counts") or {}).get("simulation", 0))
                + int(dict(summary.get("kind_counts") or {}).get("strategy_lab", 0))
            ),
            "delta": "Paper / evidence analysis jobs",
        },
    ],
    aside_title="Use This Page To",
    aside_lines=[
        "Read the latest safety and drift findings",
        "Inspect paper simulation artifacts",
        "Review strategy-lab recommendations",
        "Keep copilot output separate from live controls",
    ],
)

render_prompt_actions(
    title="Copilot Shortcuts",
    prompts=[
        "Summarize the latest safety audit.",
        "Explain the most recent drift warning.",
        "What does the newest strategy-lab report recommend?",
        "Which simulation report should I inspect first?",
    ],
    key_prefix="copilot_reports",
)

render_section_intro(
    title="Artifact Browser",
    subtitle="Newest artifacts first. Use the JSON payload for exact fields and the Markdown view for the human-oriented summary.",
    meta=f"Latest generated at {str(summary.get('latest_generated_at') or 'unknown')}",
)

if not reports:
    st.info("No copilot reports are available yet. Run one of the AI copilot jobs first.")
else:
    labels = [
        f"{str(row.get('kind') or 'unknown').replace('_', ' ').title()} · {str(row.get('severity') or 'unknown')} · {str(row.get('generated_at') or row.get('stem') or '')}"
        for row in reports
    ]
    selected_label = st.selectbox("Choose a report", labels, index=0)
    selected_idx = labels.index(selected_label)
    selected = reports[selected_idx]
    bundle = load_copilot_report_bundle(str(selected.get("stem") or ""))
    payload = dict(bundle.get("payload") or {})
    severity = str(selected.get("severity") or "unknown")
    kind = str(selected.get("kind") or "unknown")
    focus = build_copilot_report_focus(kind=kind, severity=severity, payload=payload)

    st.caption(
        f"Kind: {kind.replace('_', ' ').title()} · "
        f"Severity: {severity} · "
        f"File: {str(selected.get('stem') or '')}"
    )

    tone = str(focus.get("tone") or "info")
    message = str(focus.get("message") or "").strip()
    if message:
        if tone == "error":
            st.error(message)
        elif tone == "warning":
            st.warning(message)
        elif tone == "success":
            st.success(message)
        else:
            st.info(message)

    overview_col, counts_col = st.columns(2)
    with overview_col:
        st.markdown("#### Summary")
        st.write(str(payload.get("summary") or "No summary recorded."))
    with counts_col:
        st.markdown("#### Snapshot")
        st.write(
            {
                "kind": str(selected.get("kind") or "unknown"),
                "severity": str(selected.get("severity") or "unknown"),
                "generated_at": str(selected.get("generated_at") or ""),
            }
        )

    focus_details = dict(focus.get("details") or {})
    if kind == "strategy_lab" and focus_details:
        st.markdown("#### Evidence Runtime")
        st.write(
            {
                "status": str(focus_details.get("status") or "unknown"),
                "completed_strategies": int(focus_details.get("completed_strategies") or 0),
                "total_strategies": int(focus_details.get("total_strategies") or 0),
                "summary": str(focus_details.get("summary_text") or ""),
            }
        )

    markdown_tab, json_tab = st.tabs(["Markdown", "JSON"])
    with markdown_tab:
        markdown = str(bundle.get("markdown") or "").strip()
        if markdown:
            st.markdown(markdown)
        else:
            st.info("No Markdown companion file was found for this report.")
    with json_tab:
        st.json(payload)
