"""align_models_with_stubs

Revision ID: d3e640663448
Revises: 0001_initial_starter
Create Date: 2026-03-11 12:24:34.261787
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3e640663448'
down_revision: Union[str, Sequence[str], None] = '0001_initial_starter'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('archive_provider', sa.String(length=50), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_snapshots_content_hash'), 'archive_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_archive_snapshots_snapshot_time'), 'archive_snapshots', ['snapshot_time'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timeline', sa.String(length=20), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_source_name'), 'documents', ['source_name'], unique=False)
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_documents_timeline'), 'documents', ['timeline'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timeline', sa.String(length=20), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_asset_symbol'), 'events', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_events_event_time'), 'events', ['event_time'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_source_document_id'), 'events', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_events_timeline'), 'events', ['timeline'], unique=False)
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_table('kill_switch_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_switch_events_workspace_id'), 'kill_switch_events', ['workspace_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_zone', sa.String(length=100), nullable=True),
    sa.Column('stop_level', sa.String(length=100), nullable=True),
    sa.Column('target_logic', sa.String(length=100), nullable=True),
    sa.Column('risk_size_pct', sa.Float(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('execution_disabled', sa.Boolean(), nullable=False),
    sa.Column('mode_compatibility_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_asset_symbol'), 'recommendations', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('risk_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('max_position_size_pct', sa.Float(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_weekly_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_portfolio_exposure_pct', sa.Float(), nullable=False),
    sa.Column('max_leverage', sa.Float(), nullable=False),
    sa.Column('max_asset_concentration_pct', sa.Float(), nullable=False),
    sa.Column('max_correlated_exposure_pct', sa.Float(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('max_slippage_pct', sa.Float(), nullable=False),
    sa.Column('max_spread_pct', sa.Float(), nullable=False),
    sa.Column('min_liquidity_usd', sa.Float(), nullable=False),
    sa.Column('approval_required_for_live', sa.Boolean(), nullable=False),
    sa.Column('approval_required_above_size_pct', sa.Float(), nullable=False),
    sa.Column('approval_required_for_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('approval_required_for_futures', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_limits_workspace_id'), 'risk_limits', ['workspace_id'], unique=False)
    op.create_table('risk_status_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_status', sa.String(length=20), nullable=False),
    sa.Column('exposure_used_pct', sa.Float(), nullable=False),
    sa.Column('drawdown_today_pct', sa.Float(), nullable=False),
    sa.Column('drawdown_week_pct', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('blocked_trades_count', sa.Integer(), nullable=False),
    sa.Column('active_warnings_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_status_snapshots_ts'), 'risk_status_snapshots', ['ts'], unique=False)
    op.create_index(op.f('ix_risk_status_snapshots_workspace_id'), 'risk_status_snapshots', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('audit_logs', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('level', sa.String(length=20), nullable=False))
    op.add_column('audit_logs', sa.Column('message', sa.Text(), nullable=False))
    op.alter_column('audit_logs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'service_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_service_name'), 'audit_logs', ['service_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.drop_column('audit_logs', 'result')
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'details')
    op.add_column('connection_test_results', sa.Column('connection_id', sa.UUID(), nullable=True))
    op.add_column('connection_test_results', sa.Column('permissions_json', sa.JSON(), nullable=True))
    op.add_column('connection_test_results', sa.Column('balances_loaded', sa.Boolean(), nullable=False))
    op.add_column('connection_test_results', sa.Column('spot_supported', sa.Boolean(), nullable=False))
    op.add_column('connection_test_results', sa.Column('futures_supported', sa.Boolean(), nullable=False))
    op.add_column('connection_test_results', sa.Column('raw_result_json', sa.JSON(), nullable=True))
    op.alter_column('connection_test_results', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('connection_test_results', 'connection_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('connection_test_results', 'warnings_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('connection_test_results_workspace_id_fkey'), 'connection_test_results', type_='foreignkey')
    op.add_column('exchange_connections', sa.Column('spot_supported', sa.Boolean(), nullable=False))
    op.add_column('exchange_connections', sa.Column('futures_supported', sa.Boolean(), nullable=False))
    op.add_column('exchange_connections', sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exchange_connections', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('exchange_connections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exchange_connections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('exchange_connections', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('exchange_connections', 'provider',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('exchange_connections', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('exchange_connections', 'permissions_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('exchange_connections_workspace_id_fkey'), 'exchange_connections', type_='foreignkey')
    op.add_column('exchange_credentials', sa.Column('key_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('exchange_credentials', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exchange_credentials', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('exchange_credentials_exchange_connection_id_fkey'), 'exchange_credentials', type_='foreignkey')
    op.create_foreign_key(
        'fk_exchange_credentials_exchange_connection_id',
        'exchange_credentials',
        'exchange_connections',
        ['exchange_connection_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column('explanations', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('explanations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('explanations', sa.Column('research_query_id', sa.UUID(), nullable=True))
    op.add_column('explanations', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_explanations_asset_symbol'), 'explanations', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_explanations_created_at'), 'explanations', ['created_at'], unique=False)
    op.create_index(op.f('ix_explanations_research_query_id'), 'explanations', ['research_query_id'], unique=False)
    op.create_index(op.f('ix_explanations_user_id'), 'explanations', ['user_id'], unique=False)
    op.create_index(op.f('ix_explanations_workspace_id'), 'explanations', ['workspace_id'], unique=False)
    op.drop_column('explanations', 'evidence_json')
    op.add_column('market_candles', sa.Column('quote_volume', sa.Float(), nullable=True))
    op.alter_column('market_candles', 'exchange',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('market_candles', 'interval',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('market_candles', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_market_candles_asset_symbol'), 'market_candles', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_market_candles_exchange'), 'market_candles', ['exchange'], unique=False)
    op.create_index(op.f('ix_market_candles_interval'), 'market_candles', ['interval'], unique=False)
    op.create_index(op.f('ix_market_candles_ts'), 'market_candles', ['ts'], unique=False)
    op.add_column('market_snapshots', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('open_interest', sa.Float(), nullable=True))
    op.add_column('market_snapshots', sa.Column('raw_json', sa.JSON(), nullable=True))
    op.alter_column('market_snapshots', 'exchange',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('market_snapshots', 'bid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('market_snapshots', 'ask',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('market_snapshots', 'spread',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('market_snapshots', 'volume_24h',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_market_snapshots_asset_symbol'), 'market_snapshots', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_market_snapshots_exchange'), 'market_snapshots', ['exchange'], unique=False)
    op.create_index(op.f('ix_market_snapshots_ts'), 'market_snapshots', ['ts'], unique=False)
    op.add_column('research_queries', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('research_queries', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('research_queries', 'filters_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_research_queries_asset_symbol'), 'research_queries', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_research_queries_created_at'), 'research_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_queries_user_id'), 'research_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_research_queries_workspace_id'), 'research_queries', ['workspace_id'], unique=False)
    op.add_column('settings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('settings', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('settings', 'category',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('settings', 'settings_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('ix_settings_workspace_id'), table_name='settings')
    op.create_index(op.f('ix_settings_category'), 'settings', ['category'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('workspaces', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_workspaces_owner_user_id'), 'workspaces', ['owner_user_id'], unique=False)
    op.drop_constraint(op.f('workspaces_owner_user_id_fkey'), 'workspaces', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('workspaces_owner_user_id_fkey'), 'workspaces', 'users', ['owner_user_id'], ['id'])
    op.drop_index(op.f('ix_workspaces_owner_user_id'), table_name='workspaces')
    op.alter_column('workspaces', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workspaces', 'updated_at')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_settings_category'), table_name='settings')
    op.create_index(op.f('ix_settings_workspace_id'), 'settings', ['workspace_id'], unique=False)
    op.alter_column('settings', 'settings_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('settings', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('settings', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('settings', 'user_id')
    op.drop_index(op.f('ix_research_queries_workspace_id'), table_name='research_queries')
    op.drop_index(op.f('ix_research_queries_user_id'), table_name='research_queries')
    op.drop_index(op.f('ix_research_queries_created_at'), table_name='research_queries')
    op.drop_index(op.f('ix_research_queries_asset_symbol'), table_name='research_queries')
    op.alter_column('research_queries', 'filters_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('research_queries', 'user_id')
    op.drop_column('research_queries', 'workspace_id')
    op.drop_index(op.f('ix_market_snapshots_ts'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_exchange'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_asset_symbol'), table_name='market_snapshots')
    op.alter_column('market_snapshots', 'volume_24h',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_snapshots', 'spread',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_snapshots', 'ask',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_snapshots', 'bid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_snapshots', 'exchange',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('market_snapshots', 'raw_json')
    op.drop_column('market_snapshots', 'open_interest')
    op.drop_column('market_snapshots', 'funding_rate')
    op.drop_index(op.f('ix_market_candles_ts'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_interval'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_exchange'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_asset_symbol'), table_name='market_candles')
    op.alter_column('market_candles', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_candles', 'interval',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('market_candles', 'exchange',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('market_candles', 'quote_volume')
    op.add_column('explanations', sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_explanations_workspace_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_user_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_research_query_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_created_at'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_asset_symbol'), table_name='explanations')
    op.drop_column('explanations', 'model_name')
    op.drop_column('explanations', 'research_query_id')
    op.drop_column('explanations', 'user_id')
    op.drop_column('explanations', 'workspace_id')
    op.execute(
        """
        DO $$
        DECLARE fk_name text;
        BEGIN
          SELECT c.conname INTO fk_name
          FROM pg_constraint c
          JOIN pg_class t ON t.oid = c.conrelid
          WHERE t.relname = 'exchange_credentials'
            AND c.contype = 'f'
            AND pg_get_constraintdef(c.oid) LIKE 'FOREIGN KEY (exchange_connection_id)%'
          LIMIT 1;

          IF fk_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE exchange_credentials DROP CONSTRAINT %I', fk_name);
          END IF;
        END $$;
        """
    )
    op.create_foreign_key(op.f('exchange_credentials_exchange_connection_id_fkey'), 'exchange_credentials', 'exchange_connections', ['exchange_connection_id'], ['id'])
    op.drop_column('exchange_credentials', 'is_active')
    op.drop_column('exchange_credentials', 'rotated_at')
    op.drop_column('exchange_credentials', 'key_fingerprint')
    op.create_foreign_key(op.f('exchange_connections_workspace_id_fkey'), 'exchange_connections', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('exchange_connections', 'permissions_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('exchange_connections', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('exchange_connections', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('exchange_connections', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('exchange_connections', 'updated_at')
    op.drop_column('exchange_connections', 'created_at')
    op.drop_column('exchange_connections', 'latency_ms')
    op.drop_column('exchange_connections', 'last_test_at')
    op.drop_column('exchange_connections', 'futures_supported')
    op.drop_column('exchange_connections', 'spot_supported')
    op.create_foreign_key(op.f('connection_test_results_workspace_id_fkey'), 'connection_test_results', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('connection_test_results', 'warnings_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('connection_test_results', 'connection_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('connection_test_results', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('connection_test_results', 'raw_result_json')
    op.drop_column('connection_test_results', 'futures_supported')
    op.drop_column('connection_test_results', 'spot_supported')
    op.drop_column('connection_test_results', 'balances_loaded')
    op.drop_column('connection_test_results', 'permissions_json')
    op.drop_column('connection_test_results', 'connection_id')
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_service_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.alter_column('audit_logs', 'payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('audit_logs', 'service_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('audit_logs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('audit_logs', 'message')
    op.drop_column('audit_logs', 'level')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'event_type')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_risk_status_snapshots_workspace_id'), table_name='risk_status_snapshots')
    op.drop_index(op.f('ix_risk_status_snapshots_ts'), table_name='risk_status_snapshots')
    op.drop_table('risk_status_snapshots')
    op.drop_index(op.f('ix_risk_limits_workspace_id'), table_name='risk_limits')
    op.drop_table('risk_limits')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_asset_symbol'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_kill_switch_events_workspace_id'), table_name='kill_switch_events')
    op.drop_table('kill_switch_events')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_index(op.f('ix_events_timeline'), table_name='events')
    op.drop_index(op.f('ix_events_source_document_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_time'), table_name='events')
    op.drop_index(op.f('ix_events_asset_symbol'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_timeline'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_archive_snapshots_snapshot_time'), table_name='archive_snapshots')
    op.drop_index(op.f('ix_archive_snapshots_content_hash'), table_name='archive_snapshots')
    op.drop_table('archive_snapshots')
    # ### end Alembic commands ###
