from __future__ import annotations

from typing import AsyncIterator, Protocol, Sequence

from core.events import EventBase
from core.models import Fill, Order, OrderAck, PortfolioState


class MarketDataFeed(Protocol):
    venue: str

    async def connect(self) -> None: ...
    async def subscribe(self, symbols: Sequence[str], channels: Sequence[str]) -> None: ...
    async def events(self) -> AsyncIterator[EventBase]: ...
    async def close(self) -> None: ...


class ExecutionVenue(Protocol):
    venue: str

    async def connect(self) -> None: ...
    async def place_order(self, order: Order) -> OrderAck: ...
    async def cancel_order(self, client_order_id: str) -> bool: ...
    async def fills(self) -> AsyncIterator[Fill]: ...
    async def sync_portfolio(self) -> PortfolioState: ...
    async def close(self) -> None: ...


class Reconciler(Protocol):
    async def reconcile(self) -> None: ...


class EventStore(Protocol):
    async def append(self, e: EventBase) -> None: ...
    async def tail(self) -> AsyncIterator[EventBase]: ...


class JournalStore(Protocol):
    async def record_order_ack(self, ack: OrderAck) -> None: ...
    async def record_fill(self, fill: Fill) -> None: ...
    async def load_portfolio(self) -> PortfolioState: ...
